# Generated by Django 2.2.14 on 2020-07-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsHW', '0003_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='name_group',
        ),
    ]
