# Generated by Django 2.2.14 on 2020-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsHW', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('name_group', models.CharField(max_length=64)),
            ],
        ),
    ]
